apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-app-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-app-test
  template:
    metadata:
      labels:
        app: kubernetes-app-test
    spec:
      containers:
        - name: sample-container
          image: nginx:latest
          ports:
            - containerPort: 80
